### ISSUE TITLE
How to pass NavigationRow data and display in custom cell

### ISSUE THREAD

**Issue by davidhsu1115** [bcylin/QuickTableViewController#101]
Hi, I am doing some customization with NavigationRow. I wanna use the title, detailText, icon, parameters in my custom cell. However, when I set it in configure(), it always crash due to unwrap my cell properties.

Here's my code below. Thanks!

```
class GlobalInviteTVCell: UITableViewCell {

    @IBOutlet weak var mainTitle: UILabel!
    @IBOutlet weak var subTitle: UILabel!
    @IBOutlet weak var showImage: UIImageView!
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

        // Configure the view for the selected state
    }
    
}

extension GlobalInviteTVCell: Configurable {
    
    func configure(with row: Row & RowStyle) {
        self.mainTitle.text = row.text
        self.subTitle.text = row.detailText?.text
        self.showImage.image = row.icon?.image
    }
    
    
}

```

**Comment by bcylin** [comment]
Hi @davidhsu1115, it'd be easier to look into the problems if there's also the error message.

But it looks like you need to check if the `@IBOutlet`s are properly connected to the UI components in the Interface Builder (or Storyboard).

```swift
class GlobalInviteTVCell: UITableViewCell {
    @IBOutlet weak var mainTitle: UILabel!
    @IBOutlet weak var subTitle: UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        // IBOutlets should not be nil at this point
    }
}
```

**Comment by davidhsu1115** [comment]
@bcylin Thanks for replying. Am I right to give my custom properties inside "configure()" function? 
I might have to paste the error message later, I am currently unable to access my working mac now.

**Comment by davidhsu1115** [comment]
Here's what I have been tried so far.
1. Register cell in viewDidLoad
```swift
tableView.register(UINib(nibName: "TestCell", bundle: nil), forCellReuseIdentifier: "TestCell")
```
2. Set NavigationRow and set type as TestCell
```swift
let testNavRow = NavigationRow<TestCell>(text: "AAAABBB", detailText: .none, icon: Icon.image(UIImage(named: "vvip")!), customization: set(), action: showSettings(), accessoryButtonAction: nil)
```
3. use set() function to assign text and image to my label and image view in my cell
```swift
private func set() -> ((UITableViewCell, Row & RowStyle) -> Void) {
        return { cell, row in
            
            if let testCell = cell as? TestCell {
                testCell.testLabel.text = row.text
                testCell.testImage.image = row.icon?.image
            }
        }
    }
```
4. Add it to Section and TableContents

After these steps I got this fatal error saying I found nil while implicitly unwrapping an Optional value.
![截圖 2021-12-13 上午11 22 50](https://user-images.githubusercontent.com/10396887/145747458-4c839cc3-c077-4b5e-aac2-527e2e541be9.png)


Is there anything I forget to do causing this kind of situation?

**Comment by bcylin** [comment]
> Is there anything I forget to do causing this kind of situation?

Chances are you might have forgotten to connect the `@IBOutlet`s to the UI components in the Interface Builder.

**Comment by davidhsu1115** [comment]
I did connect the ```@IBOutlet``` to the UIComponent in storyboard. However I found out that ```set()``` function was executed before awakeFromNib. I think this might be the reason why the ```IBOutlet``` are nil.

**Comment by bcylin** [comment]
If you register the cell using a nib file, `func awakeFromNib()` should be called when the cell is dequeued with row.cellReuseIdentifier. 

There might be something wrong with the cell registration. You can check if the registered identifier matches the one for [cell dequeuing](https://github.com/bcylin/QuickTableViewController/blob/a6ebaf2098334acbadb5c1297618a2f44adcf547/Source/QuickTableViewController.swift#L112-L114):

```swift
NavigationRow<TestCell>(text: "...", detailText: .none, customization: { cell, row in
    print(row.cellReuseIdentifier)
}, action: { _ in })
```
