### ISSUE TITLE
random cell being highlighted

### ISSUE THREAD

**Issue by UnknownCoder807** [bcylin/QuickTableViewController#103]
This is on tvOS

I have a cell that when clicked on, shows an alert where the user can select from a series of options.

When the user clicks on an option and the alert is dismissed, the cell that the user clicked on is no longer highlighted, a random one is highlighted instead.  Is there anyway this can be fixed please?

**Comment by bcylin** [comment]
Hi, I'll need more info to identify the issue. Do you mind sharing some sample code that can reproduce the problem?
