### ISSUE TITLE
Any option to mount the tableview to a UIView?

### ISSUE THREAD

**Issue by EdmundLeex** [bcylin/QuickTableViewController#17]
If I want to place the table view at a specific spot, how can I do that?

I currently kinda just hack it by adding a `parentView` open var in `QuickTableViewController`. Then I have the option to set the `parentView`.

```swift
// viewDidLoad
parentView = parentView ?? view
parentView?.addSubview(tableView)
```

Does this library already provide a way to do it that I just didn't know?

**Comment by bcylin** [comment]
I think an easier way to do this is to embed the `QuickTableViewController` inside another view controller:

```swift
class ParentViewController: UIViewController {

  private lazy var childViewController: QuickTableViewController = QuickTableViewController()

  override func viewDidLoad() {
    super.viewDidLoad()
    childViewController.tableView.frame = // set the frame to a specific spot
    view.addSubview(childViewController.tableView)

    // Other container view controller management, such as:
    // addChildViewController(childViewController)
    // childViewController.didMove(toParentViewController: self)
  }

}
```

**Comment by EdmundLeex** [comment]
This should work. Thanks. 
But I feel like it might be a better api if it can be easily mounted as a child to any view.

**Comment by EdmundLeex** [comment]
What do you think about something like this
```swift
override func viewDidLoad() {
  super.viewDidLoad()
  self.parentView = uiView
  self.setupTableView()
}
```

I am doing something quite similar. And it's quite easy to reason about. The only change would just be moving the setup logic out of `viewDidLoad`, and adding a `parentView` public var. Let me know what you think. Happy to put together a PR.

**Comment by bcylin** [comment]
This is also a nice way to achieve what you need. The `tableView` is already a subview of a parent view, which is the `controller.view`.  I think it's possible to do so without any modification:

```swift
class YourViewControlller: QuickTableViewController {

  override func viewDidLoad() {
    super.viewDidLoad()
    // the tableView is a subview of self.view
    tableView.frame = // a specific spot
  }

}
```

**Comment by EdmundLeex** [comment]
I can try this out. As a beginner hacking things together, I am using a storyboard. That's why the view way is easy for me.

**Comment by EdmundLeex** [comment]
@bcylin that works great. Thanks!
