### ISSUE TITLE
Xcode 10 , Swift 4.2 error

### ISSUE THREAD

**Issue by ETHANAIR** [bcylin/QuickTableViewController#18]
<img width="569" alt="2018-09-19 4 40 39" src="https://user-images.githubusercontent.com/8438205/45741671-c4ba6b80-bc2a-11e8-8130-fca51fa9e153.png">

**Comment by bcylin** [comment]
Thanks for reporting the issue. Can you try `v1.0.0` and see if it solves the problem?
