### ISSUE TITLE
tvOS UI Testing

### ISSUE THREAD

**Issue by bcylin** [bcylin/QuickTableViewController#21]
Set up a tvOS UI testing target with [basic tests](https://github.com/bcylin/QuickTableViewController/blob/7c45dcdc08c1826006912449c250e17b147d52b8/Example-iOSUITests/ExampleUITests.swift#L39-L85).

**Comment by bcylin** [comment]
Thanks for being interested in this project. Please feel free to create a pull request. 👍

**Comment by FraDeliro** [comment]
Opened PR #27

**Comment by bcylin** [comment]
Thanks @FraDeliro, I'll review and comment soon.

**Comment by FraDeliro** [comment]
Thank you 👍
