### ISSUE TITLE
LinkCell / LinkRow

### ISSUE THREAD

**Issue by getaaron** [bcylin/QuickTableViewController#22]
This is a feature request for `LinkCell` and `LinkRow` to mimic the links sometimes used in the iOS Settings app.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/789577/46571495-8356e980-c9a8-11e8-8c73-8cc28d3e263f.png">

**Comment by bcylin** [comment]
This seems to be a `UITextView` with `attributedText` in the section (or table view) footer?

**Comment by getaaron** [comment]
Maybe, we could use a `UIButton` so it would have a touch-down state?

**Comment by bcylin** [comment]
A `UIButton` would be all right. I think it's easier to layout the link-like text in a customized footer view. 
But if it's supposed to be a cell, using a `TapActionRow` with a different cell style should be sufficient?

**Comment by getaaron** [comment]
It does look more like footer text. If it were a table cell it might have an undesirable row selection color?
