### ISSUE TITLE
SliderCell / SliderRow

### ISSUE THREAD

**Issue by getaaron** [bcylin/QuickTableViewController#23]
This is a feature request for slider settings (like in brightness or text size) to manage a discrete value within a specific range

![image](https://user-images.githubusercontent.com/789577/46571546-5f47d800-c9a9-11e8-9688-ccc6d5481c2d.png)

![](http://cdn.iphonehacks.com/wp-content/uploads/2014/09/iphone-6-display-zoom-settings.jpg)

**Comment by getaaron** [comment]
@bcylin I made an initial implementation here https://github.com/getaaron/QuickTableViewController/pull/new/slider-cell (no tests yet)

Here's how it looks:

![slider](https://user-images.githubusercontent.com/789577/46576968-9222b800-ca0b-11e8-81f4-b1d07b92545d.gif)

Notice an issue with the UINavigationController's pop gesture recognizer at the end

**Comment by bcylin** [comment]
The implementation looks good 👍 I've got a few thoughts:

* Once you build this feature, there probably will be requests for sliding fixed increments. You might want to consider that as well.
* It's better to separate `row.icon` and `row.minimumValueIcon`. Keeping `row.icon` only for table view cell's image can prevent unexpected confusion.
* The initializer is getting too long, how about using tuples for some of the parameters?

```swift
protocol SliderRowCompatible: Row, RowStyle {
  var value: Float { get set }
  var valueLimits: (min: Float, max: Float) { get }
  var valueImages: (min: UIImage?, max: UIImages?) { get }
}
```

I don't have a good idea for the pop gesture recognizer. Maybe a larger padding could be one of the solutions?

**Comment by alamodey** [comment]
Slider looks awesome, when will it be rolled out?

**Comment by getaaron** [comment]
I'm closing this since nobody seems to be working on it but the WIP source code I wrote can be found here if anyone wants to pick it back up in the future

https://github.com/Provenance-Emu/Provenance/blob/develop/Provenance/Settings/Cells/SliderCell.swift

cc @alamodey @bcylin
