### ISSUE TITLE
3D Touch

### ISSUE THREAD

**Issue by getaaron** [bcylin/QuickTableViewController#24]
This is a feature request for being able to peek/pop on a `TapActionCell` cell that presents something modally to be able to "preview" the view controller

**Comment by FraDeliro** [comment]
I can take it ;) Thanks.

**Comment by bcylin** [comment]
Any thoughts on the possible interface of this feature?

**Comment by bcylin** [comment]
I suppose QuickTableViewController needs to implement a default `UIViewControllerPreviewingDelegate` behaviour in order to support this feature, such as:

```swift
extension QuickTableViewController: UIViewControllerPreviewingDelegate {

  func previewingContext(previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController? {
    guard let indexPath = tableView.indexPathForRowAtPoint(location) else {
      return nil
    }

    let row = tableContents[indexPath.section].rows[indexPath.row]

    // If row.configurePopController is (inout UIViewController?, Row),
    // where should the UIViewController come from?
  }

}
```

The difficulty is `UIViewControllerPreviewingDelegate` involves setups on both the previewing context and view controller. One possible way is having the action closure could as `(Row) -> UIViewController?` ?

I like the idea of having different `RowActionType`s, this could also be a solution for supporting `tableView(_:accessoryButtonTappedForRowWith:)`.

**Comment by FraDeliro** [comment]
> I suppose QuickTableViewController needs to implement a default UIViewControllerPreviewingDelegate behaviour in order to support this feature

Totally agree with this solution 👍 

> One possible way is having the action closure could as (Row) -> UIViewController? ?

Thinking on the void return of the closure I haven't thought in the possibility to return directly the UIViewController, but I find it a great solution 👍
I will open a pull request when ready with this kind of implementation and we can discuss it ;)
Thanks!

**Comment by getaaron** [comment]
I think I like that interface also. An added benefit is we could potentially offer the feature on navigation rows as well as tap action rows.

**Comment by bcylin** [comment]
Were you suggesting that the row only carries a closure to `configurePopController: (inout UIViewController?, Row)` without a `UIViewControllerPreviewingDelegate` implementation?

I was trying to point out that it might be difficult to implement a default peek/pop behaviour, if you consider customizing the previewing context's source rect, etc. The QuickTableViewController subclass will still have to override the `UIViewControllerPreviewingDelegate` methods to tweak those behaviours. 

You're welcome to try the idea to see how it works, but it's also fine to keep it simple. 👍

**Comment by FraDeliro** [comment]
I opened a WIP PR #29 where I tried to follow your suggestions and the idea of a RowActionType to manage the different actions, I think that this feature could be challenging and interesting but I totally agree with you that we have to keep it simple 👍
