### ISSUE TITLE
TextFieldRow type?

### ISSUE THREAD

**Issue by d2kagw** [bcylin/QuickTableViewController#32]
Love the library.
Is there any plan to support something like a text field row?
Or am I missing something?

**Comment by bcylin** [comment]
There isn't a plan for it now, but it's a good idea. Please feel free to share your thoughts on how it can be implemented. Thanks!

**Comment by fabiosoft** [comment]
any news on this?

**Comment by bcylin** [comment]
There isn't a plan for this specific row type at the moment. 

But a cell that contains a UITextField should be sufficient:

```swift
NavigationRow<TextFieldContainerCell>(text: "", detailText: .none, action: nil)
```

UITextFieldDelegate methods can be managed in the view controller.
