### ISSUE TITLE
How do I change the section colours and fonts?

### ISSUE THREAD

**Issue by snappycode1** [bcylin/QuickTableViewController#46]
The section headers font between rows on tvOS is a little small.  Is there a way to override this like I can for the row colours?

thanks.

**Comment by bcylin** [comment]
Hi @snappycode1, this [UITableViewDelegate method](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614901-tableview) might be what you are looking for.

```swift
class ViewController: QuickTableViewController {

  func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
    // Return your customised view for section headers
  }

}
```

**Comment by snappycode1** [comment]
Perfect, thanks.  I got it to work great.
