### ISSUE TITLE
Possible to identify individual rows?

### ISSUE THREAD

**Issue by joshbeitler** [bcylin/QuickTableViewController#7]
I'm wondering if there is a way currently with this library to allow for the identification of individual rows, for example in a case where you might have multiple navigation rows with the same style, but want to do something conditionally to each one. In my case, I am wanting to tint the icons of each row and hoping to not have to resort to creating pre-colored icon images for each different row. Normally you could use the reuse identifier to achieve something like this, but it seems like that is tied up here.

**Comment by bcylin** [comment]
This might be the use case I didn't think of. If I understand the issue correctly, one approach might be creating customised navigation row types that conform to the `Row` protocol. They can have `cellReuseIdentifier`s registered with different cell classes.

**Comment by joshbeitler** [comment]
Thanks for the response, this was about what I was thinking of doing.
