### ISSUE TITLE
How to make images fit into table cells properly

### ISSUE THREAD

**Issue by alamodey** [bcylin/QuickTableViewController#71]
I want to add icons next to my settings items neatly like in the below screenshot. But at the moment, only the SF Symbols are in the correct size. When I add a custom image, it's always too big and tries to almost the entire height of the row. Is there an elegant way to do this? Please show an example. 

![IMG_9EAD7E82536F-1](https://user-images.githubusercontent.com/55496019/94682012-a8984b80-0367-11eb-9620-682ebeb738a6.jpeg)

**Comment by bcylin** [comment]
The easiest way is to export the image to the 1x size you need. Then it should be the correct size when set as the icon.

There are also various ways to resize images at runtime if that's what you are looking for.
