### ISSUE TITLE
Unability to use the library in iOS12 project

### ISSUE THREAD

**Issue by svoip** [bcylin/QuickTableViewController#81]
I made a new project that goes from iOS12 to recent iOS14.2.
I import this library as Swift package, using version 1.2.3.

When I import this library in my class,
`import QuickTableViewController`

I get the following build error:
Compiling for iOS 12.4, but module 'QuickTableViewController' has a minimum deployment target of iOS 13.0: /Users/ME/Library/Developer/Xcode/DerivedData/MYAPP-goddzpszwntzcgakkvpsksjrjqsi/Build/Products/Debug-iphonesimulator/QuickTableViewController.swiftmodule/x86_64-apple-ios-simulator.swiftmodule.

I check the library's Package.swift, it supports iOS9 and up.
But then I noticed 
`swiftLanguageVersions: [.v5]`

Could it be due to this line that library implicitly supports iOS13 and up, while defining the upper lines?
```
  platforms: [
        .iOS(.v9),
        .tvOS(.v9),
    ]
```
Thanks

**Comment by svoip** [comment]
Update: 
I checked out this branch, which resolves my issue.
`feature/minimum-deployment-target`

I will close this issue.
Thanks

**Comment by bcylin** [comment]
@svoip sorry for the inconvenience. I forgot to cut a release for the [Package.swift updates](https://github.com/bcylin/QuickTableViewController/commit/cbf1df8798cbd8f8a2335b4c0f7e53423c6630da). `v1.3.1` is out now.

I'm about to delete the branch `feature/minimum-deployment-target` in a few days. Please use `v1.3.1` instead.
