### ISSUE TITLE
How to specify "alwaysSelectsOneOption" in RadioSection

### ISSUE THREAD

**Issue by benhaldenby** [bcylin/QuickTableViewController#84]
Hi,

Forgive the noobie question, I am a beginner at Swift and iOS dev. Where do I specify the `alwaysSelectsOneOption` in `RadioSection` declaration? I can't find any examples in the source code or docs.

```
RadioSection(title: "Audio Quality", options: [
    OptionRow(
        text: "Medium",
        isSelected: userAudioQuality == "medium" ? true : false,
        action: didToggleQuality(quality: "medium")
    ),
    OptionRow(
        text: "High",
        isSelected: userAudioQuality == "high" ? true : false,
        action: didToggleQuality(quality: "high")
    ),
]),
```

Thanks,
Ben

**Comment by bcylin** [comment]
Hi, no worries at all.

To set `alwaysSelectsOneOption`, you need a reference to the `RadioSection` instance. The variable can later be used in the table contents after the configuration.

```swift
let radioSection = RadioSection(...)
radioSection.alwaysSelectsOneOption = true

tableContents = [radioSection]
```

**Comment by benhaldenby** [comment]
Brilliant, thank you!
