### ISSUE TITLE
Update the icon property of a NavigationRow

### ISSUE THREAD

**Issue by benhaldenby** [bcylin/QuickTableViewController#85]
Hi,

Is it possible to update the icon property of a NavigationRow with the option that was chosen in the view I navigated to?

This is my starting view, which has the action to push another view controller onto the stack. `getCurrentAppIcon()` in this view checks `UIApplication.shared.alternateIconName` and returns a named icon. The detail view just sets a new AlternateIcon. But I want the first view to show the newly chosen icon when I tap "< Back" in the nav bar.

```
Section(title: "App Icon", rows: [
    NavigationRow(
        text: "App Icon",
        detailText: .none,
        icon: getCurrentAppIcon(),
        action: { [weak self] _ in
        self?.navigationController?.pushViewController(SettingsAppIconViewController(), animated: true)
    })
]),
```

Thanks
Ben

**Comment by bcylin** [comment]
QuickTableViewController isn't designed for dynamic contents so it's not recommended to use it this way. However, it can be achieved by recreating the table contents when needed:

```swift
final class ViewController: QuickTableViewController {
    func viewDidLoad() {
        super.viewDidLoad()
        reloadTableContents()
    }

    private func reloadTableContents() {
        tableContents = ...
    }
}

extension ViewController: SettingsAppIconViewControllerDelegate {
    func settingsAppIconViewControllerDidUpdateAppIcon(_ controller: SettingsAppIconViewController) {
        reloadTableContents()
    }
}
```

**Comment by benhaldenby** [comment]
Hi, thanks for your answer, it's very helpful.

Xcode says "Cannot find type 'SettingsAppIconViewControllerDelegate' in scope" on the extension definition. 
I tried defining a protocol called SettingsAppIconViewControllerDelegate, which fixed the earlier error, but could you explain how I call settingsAppIconViewControllerDidUpdateAppIcon() ?

Thanks

**Comment by bcylin** [comment]
It's a way for your SettingsAppIconViewController to inform others about changes, just like [UIImagePickerControllerDelegate](https://developer.apple.com/documentation/uikit/uiimagepickercontrollerdelegate). It'd be something like:

```swift
final class SettingsAppIconViewController: UIViewController {
    weak var delegate: SettingsAppIconViewControllerDelegate?

    private func userDidChangeAppIcon() {
        delegate?.settingsAppIconViewControllerDidUpdateAppIcon(self)
        // or delegate?.settingsAppIconViewController(self, didUpdateAppIcon: ...) depending how you'are going to sync the data
    }
}
```

Then SettingsAppIconViewController's delegate can be assigned before it's presented:

```swift
final class ViewController: QuickTableViewController, SettingsAppIconViewControllerDelegate {
    private func showAppIconSettings() {
        let controller = SettingsAppIconViewController()
        controller.delegate = self
        navigationController?.pushViewController(controller, animated: true)
    }
}
```

**Comment by benhaldenby** [comment]
Thanks for your help!
