### ISSUE TITLE
Reloading table stops animation

### ISSUE THREAD

**Issue by Joebayld** [bcylin/QuickTableViewController#9]
I've found when interacting with a SwitchRow that because it's telling the tableView to reload it's data, It stops the animation of the UIControl. You can really notice it when flipping a switch. 

As a solution, I think it's best not to always reload the table just when you want to update the dataSource. It always updates because you implement the didSet of the source. Perhaps we give an option to perform a silent update? That way we can still update the source without forcing a redraw.

**Comment by bcylin** [comment]
Thanks for reporting this issue. When the switch is toggled, the original row is replaced with a new one. Maybe it's time to change the rows from structs to classes so the values can be updated on the same objects. 

I made some changes on [this branch](https://github.com/bcylin/QuickTableViewController/tree/feature/row-objects). Can you take a look to see if it fixes the problem?

```rb
pod "QuickTableViewController",
  git: "https://github.com/bcylin/QuickTableViewController.git",
  branch: "feature/row-objects"
```
