### ISSUE TITLE
How to disable deselecting radio buttons?

### ISSUE THREAD

**Issue by alamodey** [bcylin/QuickTableViewController#91]
I want to be able to make the radio buttons act like compulsory radio buttons where there is something selected. So if someone presses a button that is already selected, I don't want to select that row. How do I do this?

**Comment by alamodey** [comment]
I think it relates to this section but can't figure out how I should modify it:

```
  /// The state of selection.
  public var isSelected: Bool = false {
    didSet {
      guard isSelected != oldValue else {
        return
      }
      DispatchQueue.main.async {
        self.action?(self)
      }
    }
  }
```

**Comment by bcylin** [comment]
There's a configuration in [`RadioSection`](https://bcylin.github.io/QuickTableViewController/Classes/RadioSection.html#/s:24QuickTableViewController12RadioSectionC22alwaysSelectsOneOptionSbvp) that might be what you need.

```swift
let radioSection = RadioSection(...)
radioSection.alwaysSelectsOneOption = true
```
