### ISSUE TITLE
How to reload the settings menu

### ISSUE THREAD

**Issue by alamodey** [bcylin/QuickTableViewController#92]
Hi, I need to be able to programatically reload the settings view for two reasons:
- some users are confused after they upgrade to premium that the menu still has options disabled as though they are not premium users
- I have using this NavigationRow(text: "CellStyle", detailText: .value2(".value2")) and after a user selects a new option for .value2 I want my settings menu to display the new value instead of the initial one loaded at app launch

Is it possible to reload the menu? Thanks.

**Comment by bcylin** [comment]
I suppose by "reload the menu", it means reloading the table view?

Updating `tableContent` reloads the table view so you can recreate table contents whenever the setting's value changes.

```swift
class ViewController: QuickTableViewController {
    private var settingsValue = SettingsValue() {
        didSet {
            tableContent = recreateTableContent()
        }
    }
}

extension ViewController: AnotherViewControllerDelegate {
    func anotherViewController(_ controller: AnotherViewController, didUpdateSettingsValue value: SettingsValue) {
        settingsValue = value
    }
}
```

**Comment by alamodey** [comment]
I am a bit confused by this, are you able to update your code base so it automatically reloads, or at least gives the option to?

Alternatively I tried to just re-create the table in viewDidAppear - it works, except there's a bit of lag so you can see the  .value2 text change from the previous value to the new one.

**Comment by bcylin** [comment]
If you recreate the table content in `viewDidAppear(_:)`, the table view reloads _after_ the view appears.

Basically recreating the `tableContent` reloads the table view. Where and when to update the `tableContent` depends on your business logic.

**Comment by alamodey** [comment]
Ah thanks for pointing that out. I just re-drew the table in viewWillAppear instead and it works fine. 🙂
