### ISSUE TITLE
How can I change selected and deselect accessoryView image?

### ISSUE THREAD

**Issue by davidhsu1115** [bcylin/QuickTableViewController#99]
As title, I was hoping to change the select and deselect image for my menu. However if I use original table view delegate "didSelect" and "deSelect" method, multi-selection section stop working.
Is there a proper way to change it. Thx

**Comment by davidhsu1115** [comment]
Update: This is my custom cell, I was hoping to use select and deselect to trigger setSelect function in cell class

```
class TestCell: UITableViewCell {

  @IBOutlet weak var testImageView: UIImageView!
  
  override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

      testImageView.image = selected ? UIImage(named: "iconmonstr-x-mark") : UIImage()
    }
    
}

```

**Comment by bcylin** [comment]
Hi, can you share your `func tableView(_:didSelectRowAt:)` setup where the multi-selection section stops working?

**Comment by davidhsu1115** [comment]
Hi, there is my code, just simply print out the index.
The functionality I am trying to approach is to change the accessory view image from checkmark to my custom icon. So I use the didSelect and deselect function to control it.

```
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

    print("select \(indexPath)")
  }

  func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {

    print("deselect \(indexPath)")
  }
```

**Comment by bcylin** [comment]
Looks like you need to call super when you override a method. Otherwise, it will override the existing behaviour.

```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    super.tableView(tableView, didSelectRowAt: indexPath)
}
```

**Comment by davidhsu1115** [comment]
I tried and add call super in my code, and the multiple selection become single select, I found out if I use the original table view delegate, multiple selection won't work.

Here is my code. Thx a lot!

```
  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

    super.tableView(tableView, didSelectRowAt: indexPath)
    if let cell = tableView.cellForRow(at: indexPath) as? TestCell {
      cell.testImageView.image = #imageLiteral(resourceName: "iconmonstr-x-mark")
    }

    print("select \(indexPath)")
  }

  func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {
    
    if let cell = tableView.cellForRow(at: indexPath) as? TestCell {
      cell.testImageView.image = UIImage()
    }
    print("deselect \(indexPath)")
  }
```

**Comment by davidhsu1115** [comment]
But I need the original delegate in order to use setSelected to set custom image for replacing the checkmark.

**Comment by bcylin** [comment]
In this case, the cell's accessory type is controlled by the [`optionRow.isSelected`](https://github.com/bcylin/QuickTableViewController/blob/a6ebaf2098334acbadb5c1297618a2f44adcf547/Source/Rows/OptionRow.swift#L95-L98), not `tableViewCell.isSelected`, which is a brief UI state that's not preserved.

Perhaps you don't need to change `tableView(_:didSelectRowAt:)` and `tableView(_:didDeselectRowAt:)` at all. Instead in the custom cell class, you can set the accessory view based on the option's selection:

```swift
class CustomOptionCell: UITableViewCell, Configurable {
  func configure(with row: Row & RowStyle) {
    guard let isOptionSelected = (row as? OptionRowCompatible)?.isSelected else { return }
    accessoryView = isOptionSelected ? UIImageView(image: #imageLiteral(resourceName: "iconmonstr-x-mark")) : nil
  }
}
```

```swift
tableContents = [
  RadioSection(title: "Radio Buttons", options: [
    OptionRow<CustomOptionCell>(text: "Option 1", isSelected: true, action: ...),
    OptionRow<CustomOptionCell>(text: "Option 2", isSelected: false, action: ...)
  ])
]
```

**Comment by davidhsu1115** [comment]
Thanks for your reply, I will try your solution today.

**Comment by davidhsu1115** [comment]
It works perfectly! Thank you so much.
Just out of curiosity does this framework support max selecting count for multiple selection?

**Comment by bcylin** [comment]
> Just out of curiosity does this framework support max selecting count for multiple selections?

No, it doesn't.

Radio buttons are like HTML `<input type="radio">`. Only one radio button in a group can be selected at the same time. A section with multiple selections is a different concept.

But you can create a `Section` subclass that does what you need. It should be similar to `RadioSection`:

```swift
final class CheckboxSection: Section {

  init(title: String?, options: [OptionRowCompatible], footer: String? = nil) {
    self.options = options
    super.init(title: title, rows: [], footer: footer)
  }

  private(set) var options: [OptionRowCompatible]

  override var rows: [Row & RowStyle] {
    get { options }
    set { options = newValue as? [OptionRowCompatible] ?? options }
  }

  private var selectedOptions: [OptionRowCompatible] {
    options.filter(\.isSelected)
  }

  var maxNumberOfSelections: Int = 2

  func toggle(_ option: OptionRowCompatible) -> IndexSet {
    guard let index = options.firstIndex(where: { $0 === option }) else {
      return []
    }

    if !option.isSelected && selectedOptions.count == maxNumberOfSelections {
      return []
    }

    option.isSelected = !option.isSelected
    return IndexSet([index])
  }

}
```

```swift
final class ViewController: QuickTableViewController {

  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    let section = tableContents[indexPath.section]
    let row = section.rows[indexPath.row]

    switch (section, row) {
    case let (checkboxes as CheckboxSection, option as OptionRowCompatible):
      let changes: [IndexPath] = checkboxes.toggle(option).map {
        IndexPath(row: $0, section: indexPath.section)
      }
      if changes.isEmpty {
        tableView.deselectRow(at: indexPath, animated: false)
      } else {
        tableView.reloadRows(at: changes, with: .automatic)
      }

    default:
      super.tableView(tableView, didSelectRowAt: indexPath)
    }
  }

}
```

**Comment by davidhsu1115** [comment]
WOW thank you so much for this comprehensive reply !!
I will try it.
